### ISSUE TITLE
rx888_stream doesn't compile on gcc (Debian 10.2.1-6) 10.2.1 20210110

### ISSUE THREAD

**Issue by ka9q** [rhgndf/rx888_stream#2]
Two syntax errors: the entire case 'g': entry on line 220 needs to be wrapped in {braces}, and the default: entry on line 260 needs to be followed with a ';' (null statement).

**Comment by rhgndf** [comment]
Fixed in 5f650d40be5541176e10c2bfd9b7f5a32757d687
