### ISSUE TITLE
Trivial errors under macos compiler (but not gcc)

### ISSUE THREAD

**Issue by ka9q** [rhgndf/rx888_stream#4]
cc rx888_stream.c ezusb.c -o rx888_stream -ggdb3 -O3 -march=native -Wall -Werror -Wpedantic -fstack-protector-all `pkg-config --cflags --libs libusb-1.0`
In file included from rx888_stream.c:25:
In file included from ./ezusb.h:32:
./rx888.h:137:7: error: no newline at end of file [-Werror,-Wnewline-eof]
#endif
      ^
rx888_stream.c:129:15: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void printhelp() {
              ^
               void
2 errors generated.
In file included from ezusb.c:31:
In file included from ./ezusb.h:32:
./rx888.h:137:7: error: no newline at end of file [-Werror,-Wnewline-eof]
#endif
      ^
1 error generated.

**Comment by rhgndf** [comment]
Fixed in 9a70fd1. Does this work in macos?

**Comment by ka9q** [comment]
It compiles on macos now. Do you mean does it execute? I haven't actually tried it yet. I will.
