### ISSUE TITLE
Could not find or open bootloader

### ISSUE THREAD

**Issue by dividebysandwich** [rhgndf/rx888_stream#6]
My RX888MK2 is not recognized on linux mint:

lsusb output:
```
Bus 001 Device 008: ID 04b4:00f3 Cypress Semiconductor Corp. FX3 micro-controller (DFU mode)
```

Error message:

```
$ rx888_stream -f SDDC_FX3.img -r --sample-rate 100000000 -o -
thread 'main' panicked at src/main.rs:214:10:
Could not find or open bootloader
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here's the syslog when I plug in the device:

```
kernel: usb 1-9: new high-speed USB device number 9 using xhci_hcd
mtp-probe[3743]: checking bus 1, device 9: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-9"
kernel: usb 1-9: New USB device found, idVendor=04b4, idProduct=00f3, bcdDevice= 1.00
kernel: usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
kernel: usb 1-9: Product: WestBridge 
kernel: usb 1-9: Manufacturer: Cypress
kernel: usb 1-9: SerialNumber: 0000000004BE
```

I also tried downloading the latest SDDC_FX3 from the ExtIO github, no change.

**Comment by ur5fan** [comment]
I have the same problem.
**My system:**
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"

**An error message:**
PhantomSDR/rx888_stream$ ./target/release/rx888_stream -f SDDC_FX3.img -r --sample-rate 100000000 -o -
thread 'main' panicked at src/main.rs:216:10:
Could not find or open bootloader
stack backtrace:
   0:     0x5fbdcd28c112 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
   1:     0x5fbdcd2aeeac - core::fmt::write::hd9a8d7d029f9ea1a
   2:     0x5fbdcd28a01f - std::io::Write::write_fmt::h0e1226b2b8d973fe
   3:     0x5fbdcd28bee4 - std::sys_common::backtrace::print::he907f6ad7eee41cb
   4:     0x5fbdcd28d4fb - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
   5:     0x5fbdcd28d253 - std::panicking::default_hook::h25ba2457dea68e65
   6:     0x5fbdcd28d99d - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
   7:     0x5fbdcd28d872 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
   8:     0x5fbdcd28c5e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
   9:     0x5fbdcd28d5a4 - rust_begin_unwind
  10:     0x5fbdcd1eb2f5 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
  11:     0x5fbdcd2adce1 - core::panicking::panic_display::h277de99b44f66bbb
  12:     0x5fbdcd1eb2bb - core::option::expect_failed::h9d76e63e47b0f089
  13:     0x5fbdcd1ef6dc - rx888_stream::main::he5a28eb99453dd8a
  14:     0x5fbdcd20e1f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he1300aecc3df71b9
  15:     0x5fbdcd20e209 - std::rt::lang_start::{{closure}}::h05f6e79101afc824
  16:     0x5fbdcd285773 - std::rt::lang_start_internal::h103c42a9c4e95084
  17:     0x5fbdcd1fa105 - main
  18:     0x7e720b62a1ca - <unknown>
  19:     0x7e720b62a28b - __libc_start_main
  20:     0x5fbdcd1eb915 - _start
  21:                0x0 - <unknown>

**Comment by rhgndf** [comment]
Try with sudo? The application might not have enough permissions to access the device.

**Comment by ur5fan** [comment]
@rhgndf it works. Thanks a lot.

**Comment by dividebysandwich** [comment]
Aye that did the trick. For some reason I didn't even think to try this. Thanks!
